title: .dotfiles from squigz
description: config files and whatnot from <a href="https://github.com/squigglezworth"><b>@squigglezworth</b></a>

include: [ .preseed, .setup/ ]

theme: jekyll-theme-midnight
