on:
  workflow_dispatch:

jobs:
  fetch-upstream:
    runs-on: ubuntu-latest
    name: Fetch Upstream
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: squigzy/squigzy.github.io
          token: ${{ github.token }}
          fetch-depth: 0
      - name: Configure git
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "noreply@myemail.com"
          git remote add upstream https://github.com/squigglezworth/dotfiles.git
        shell: bash
      - name: Fetch and merge
        id: fetch-merge
        run: |
          git fetch upstream
          git checkout master
          lines=$( git diff master..upstream/master -- . ':(exclude).github/**' | wc -l )
          echo "Number of detected line changes: $lines"
          if [ $lines -gt 0 ]; then
            git merge upstream/master
            git push
          fi
        shell: bash
